version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-4000}
      - HOST=${HOST:-0.0.0.0}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-defaultPassword}
      - DB_MAX_SIZE_GB=${DB_MAX_SIZE_GB:-15}
      - ENABLE_ANALYTICS=${ENABLE_ANALYTICS:-false}
      - ANALYTICS_SCRIPTS=${ANALYTICS_SCRIPTS:-{}}
    volumes:
      - ptcg-sim-data:/app/server/database
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-4000}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  ptcg-sim-data:
    driver: local
